### PR TITLE
feat(locales): add French language

### PR DESCRIPTION
**Pull request by QuentinMichinot**

### CODE REVIEW

**Comment by WolfgangAl** [comment]
If you look at WeekDayHeader.vue you’ll see a computed property weekday(). It’s responsible for the text you see in the day view header. This does not link to a LOCALE_ENTRY, but to dayspan Day.js/format. (Technically, it does use a LOCALE_ENTRY but this is not the name of the day but rather the _format_ to pass to moment). If you open your packaged JS bundle and look for dayspan/lib/Day.js you’ll see something like

```
var __WEBPACK_IMPORTED_MODULE_5_moment__ = __webpack_require__(\"./dayspan-vuetify/node_modules/dayspan/node_modules/moment/moment.js\”);
```
This imports the moment lib local to dayspan. If you then add something like this
```
__WEBPACK_IMPORTED_MODULE_5_moment__.locale(\"zh-cn\");
```
(Setting the locale for this version of moment to Chinese, just so we can see which texts are actually from moment formatting and not from the dayspan-vuetify locale)

Save and reload. You should now see Chinese UI elements. And those are the same elements you described as not being translated...

Unfortunately there’s not an easy solution to this.

**Comment by WolfgangAl** [comment]
I think this leaves only the schedule summaries unlocalized. But I think there might be a problem there anyway because I think these should be defined in dayspan-vuetify but dayspan-vuetify seems to ignore all local definitions. Have to dig deeper into this though.

The missing i18n for 'More actions...' has been added by  [@deka](https://github.com/deka) in a separate [pull request](https://github.com/ClickerMonkey/dayspan-vuetify/pull/109).

**Comment by ClickerMonkey** [comment]
@QuentinMichinot @WolfgangAl  I'm adding multilingual support to dayspan so everything will be localized. Here's a document you could fill out when you have time!

https://docs.google.com/document/d/12ZVXjSJ_YsEdcafA3ITCfPv7in4A7ELCmMTaftudFEk/edit?usp=sharing

**Comment by WolfgangAl** [comment]
Can't help you there; I can read a little French but wouldn't presume to be able to translate into French...

**Pull request merged**
